# Prefer configuring with environment variables in production:
# AGENCYIMS_DB_URL, AGENCYIMS_DB_USER, AGENCYIMS_DB_PASSWORD
db.url=jdbc:mysql://localhost:3306/agencyims
db.user=root
db.password=therepenter09
